/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.synology.eric88.schedules.schedulable;

import java.io.File;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import me.synology.eric88.schedules.schedulable.utils.FileLogUtil;

/**
 * @package me.synology.eric88
 * @author Eric Chan
 */
public class Library {
  // FIXME: remove this. It is designed for testing purposes
  public static void main(String[] args) {
  }
}
